
server:
  port: 8990

spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jarvis2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.mogujie.jarvis.web.entity,;com.mogujie.jarvis.dto.generate